const KEY='glide-bookmarks-v1';
const palette=[['#5d7cff','#8a62ec'],['#ff7b6f','#ffad64'],['#20bfa9','#54d48e'],['#3975ee','#52b3ff'],['#bb5ee8','#f377b7'],['#364457','#79879a']];
const defaults={theme:'auto',active:'common',categories:[
  {id:'common',name:'常用',sites:[site('Apple','https://www.apple.com/cn/',''),site('百度','https://www.baidu.com/','百'),site('哔哩哔哩','https://www.bilibili.com/','▶')]},
  {id:'ai',name:'AI 工具',sites:[site('ChatGPT','https://chatgpt.com/','✦'),site('Claude','https://claude.ai/','C'),site('Perplexity','https://www.perplexity.ai/','P')]},
  {id:'dev',name:'开发工具',sites:[site('GitHub','https://github.com/','GH'),site('MDN','https://developer.mozilla.org/','MDN'),site('Vercel','https://vercel.com/','▲')]},
  {id:'media',name:'影音',sites:[site('YouTube','https://www.youtube.com/','▶'),site('Spotify','https://open.spotify.com/','●')]},
  {id:'mail',name:'邮箱',sites:[site('Gmail','https://mail.google.com/','M'),site('Outlook','https://outlook.live.com/','O')]},
  {id:'cloud',name:'云服务',sites:[site('iCloud','https://www.icloud.com/','☁'),site('Google Drive','https://drive.google.com/','△')]}
]};
function site(name,url,icon=''){return{id:uid(),name,url,icon}}
function uid(){return Math.random().toString(36).slice(2,10)}
function clone(v){return JSON.parse(JSON.stringify(v))}
let state=load();let query='';let dragged=null;let toastTimer;
const $=s=>document.querySelector(s);const els={sidebar:$('#sidebar'),scrim:$('#scrim'),list:$('#categoryList'),grid:$('#siteGrid'),title:$('#pageTitle'),count:$('#siteCount'),empty:$('#emptyState'),search:$('#searchInput'),siteDialog:$('#siteDialog'),categoryDialog:$('#categoryDialog')};
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.categories?.length){if(!v.iconSize)v.iconSize=36;return v}}catch{}const v=clone(defaults);v.iconSize=36;return v}
function save(message){localStorage.setItem(KEY,JSON.stringify(state));if(message)toast(message)}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1700)}
function activeCategory(){return state.categories.find(c=>c.id===state.active)||state.categories[0]}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function host(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
function colors(id){let n=[...id].reduce((a,c)=>a+c.charCodeAt(0),0);return palette[n%palette.length]}
function render(){renderCategories();renderSites();applyTheme();applyIconSize()}
function renderCategories(){els.list.innerHTML=state.categories.map(c=>`<button class="category ${c.id===state.active?'active':''}" data-id="${c.id}" draggable="true"><span>⌘</span><span>${escapeHtml(c.name)}</span><span class="count">${c.sites.length}</span><span class="cat-edit" role="button" aria-label="编辑 ${escapeHtml(c.name)}">···</span></button>`).join('')}
function renderSites(){const cat=activeCategory();if(!cat)return;els.title.textContent=query?'搜索结果':cat.name;const all=query?state.categories.flatMap(c=>c.sites.map(s=>({...s,categoryId:c.id}))):cat.sites.map(s=>({...s,categoryId:cat.id}));const sites=all.filter(s=>(s.name+' '+s.url).toLowerCase().includes(query.toLowerCase()));els.count.textContent=`${sites.length} 个网站`;els.grid.innerHTML=sites.map(s=>{const [a,b]=colors(s.id);const isImage=/^https?:\/\//i.test(s.icon);const icon=isImage?`<img src="${escapeHtml(s.icon)}" alt="" onerror="this.parentElement.textContent='${escapeHtml(s.name[0]||'?')}'">`:escapeHtml(s.icon||s.name[0]||'?');return `<article class="site-card" draggable="true" data-id="${s.id}" data-category="${s.categoryId}" style="--icon-a:${a};--icon-b:${b}"><button class="edit" aria-label="编辑 ${escapeHtml(s.name)}">•••</button><a class="site-link" href="${escapeHtml(s.url)}" target="_blank" rel="noopener"><span class="site-icon">${icon}</span><span class="site-name">${escapeHtml(s.name)}</span><span class="site-host">${escapeHtml(host(s.url))}</span></a></article>`}).join('');els.empty.hidden=sites.length>0||!!query}
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='auto'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function applyIconSize(){const size=Math.min(64,Math.max(28,Number(state.iconSize)||36));const root=document.documentElement.style;root.setProperty('--site-icon-size',size+'px');root.setProperty('--site-card-min',Math.round(98+size*.78)+'px');root.setProperty('--site-card-height',Math.round(88+size*1.1)+'px');root.setProperty('--site-card-pad',Math.round(10+size*.14)+'px');root.setProperty('--site-grid-gap',Math.round(7+size*.14)+'px');root.setProperty('--site-icon-radius',Math.round(size*.33)+'px');$('#iconSize').value=size;$('#iconSizeValue').value=size}
function fillCategories(selected){$('#siteCategory').innerHTML=state.categories.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}
function openSite(siteId,categoryId=state.active){const cat=state.categories.find(c=>c.id===categoryId);const s=cat?.sites.find(x=>x.id===siteId);$('#siteDialogTitle').textContent=s?'编辑网站':'添加网站';$('#siteId').value=s?.id||'';$('#siteName').value=s?.name||'';$('#siteUrl').value=s?.url||'';$('#siteIcon').value=s?.icon||'';fillCategories(categoryId);$('#deleteSite').hidden=!s;els.siteDialog.showModal();setTimeout(()=>$('#siteName').focus(),50)}
function openCategory(id=''){const c=state.categories.find(x=>x.id===id);$('#categoryDialogTitle').textContent=c?'编辑分类':'新建分类';$('#categoryId').value=c?.id||'';$('#categoryName').value=c?.name||'';$('#deleteCategory').hidden=!c;els.categoryDialog.showModal();setTimeout(()=>$('#categoryName').focus(),50)}
els.list.addEventListener('click',e=>{const row=e.target.closest('.category');if(!row)return;if(e.target.closest('.cat-edit'))openCategory(row.dataset.id);else{state.active=row.dataset.id;query='';els.search.value='';save();render();closeSidebar()}});
$('#addCategory').onclick=()=>openCategory();$('#addSite').onclick=()=>openSite('');$('#emptyAdd').onclick=()=>openSite('');
$('#categoryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#categoryId').value,name=$('#categoryName').value.trim();if(!name)return;if(id)state.categories.find(c=>c.id===id).name=name;else{const c={id:uid(),name,sites:[]};state.categories.push(c);state.active=c.id}save(id?'分类已更新':'分类已创建');els.categoryDialog.close();render()});
$('#deleteCategory').onclick=()=>{const id=$('#categoryId').value,c=state.categories.find(x=>x.id===id);if(state.categories.length===1)return toast('至少保留一个分类');if(c.sites.length&&!confirm(`删除“${c.name}”及其中 ${c.sites.length} 个网站？`))return;state.categories=state.categories.filter(x=>x.id!==id);if(state.active===id)state.active=state.categories[0].id;save('分类已删除');els.categoryDialog.close();render()};
$('#siteForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#siteId').value,target=$('#siteCategory').value;let url=$('#siteUrl').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;const data={name:$('#siteName').value.trim(),url,icon:$('#siteIcon').value.trim()};if(id){let found,from;state.categories.forEach(c=>{const i=c.sites.findIndex(s=>s.id===id);if(i>=0){found=c.sites.splice(i,1)[0];from=c.id}});state.categories.find(c=>c.id===target).sites.push({...found,...data});if(from!==target)state.active=target}else state.categories.find(c=>c.id===target).sites.push({id:uid(),...data});save(id?'网站已更新':'网站已添加');els.siteDialog.close();render()});
$('#deleteSite').onclick=()=>{const id=$('#siteId').value;state.categories.forEach(c=>c.sites=c.sites.filter(s=>s.id!==id));save('网站已删除');els.siteDialog.close();render()};
els.grid.addEventListener('click',e=>{const card=e.target.closest('.site-card');if(card&&e.target.closest('.edit')){e.preventDefault();openSite(card.dataset.id,card.dataset.category)}});
els.search.addEventListener('input',e=>{query=e.target.value.trim();renderSites()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();els.search.focus()}if(e.key==='Escape')closeSidebar()});
function siteDragStart(e){const card=e.target.closest('.site-card');if(!card)return;dragged={type:'site',id:card.dataset.id,from:card.dataset.category};card.classList.add('dragging');e.dataTransfer.effectAllowed='move'}
els.grid.addEventListener('dragstart',siteDragStart);els.grid.addEventListener('dragend',e=>{e.target.closest('.site-card')?.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));dragged=null});
els.grid.addEventListener('dragover',e=>{if(dragged?.type!=='site'||query)return;e.preventDefault();e.target.closest('.site-card')?.classList.add('drag-over')});
els.grid.addEventListener('dragleave',e=>e.target.closest('.site-card')?.classList.remove('drag-over'));
els.grid.addEventListener('drop',e=>{if(dragged?.type!=='site'||query)return;e.preventDefault();const target=e.target.closest('.site-card');moveSite(dragged.id,dragged.from,state.active,target?.dataset.id);render()});
els.list.addEventListener('dragstart',e=>{const row=e.target.closest('.category');if(!row)return;dragged={type:'category',id:row.dataset.id};row.classList.add('dragging');e.dataTransfer.effectAllowed='move'});
els.list.addEventListener('dragend',e=>{e.target.closest('.category')?.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));dragged=null});
els.list.addEventListener('dragover',e=>{const row=e.target.closest('.category');if(!row||!dragged)return;e.preventDefault();row.classList.add('drag-over')});els.list.addEventListener('dragleave',e=>e.target.closest('.category')?.classList.remove('drag-over'));
els.list.addEventListener('drop',e=>{const row=e.target.closest('.category');if(!row||!dragged)return;e.preventDefault();if(dragged.type==='site')moveSite(dragged.id,dragged.from,row.dataset.id);else{const from=state.categories.findIndex(c=>c.id===dragged.id),to=state.categories.findIndex(c=>c.id===row.dataset.id);const [c]=state.categories.splice(from,1);state.categories.splice(to,0,c);save('分类顺序已保存')}render()});
function moveSite(id,fromId,toId,beforeId){const from=state.categories.find(c=>c.id===fromId),to=state.categories.find(c=>c.id===toId);if(!from||!to)return;const i=from.sites.findIndex(s=>s.id===id);if(i<0)return;const [s]=from.sites.splice(i,1);let at=beforeId?to.sites.findIndex(x=>x.id===beforeId):to.sites.length;if(at<0)at=to.sites.length;to.sites.splice(at,0,s);save(fromId===toId?'网站顺序已保存':'网站已移动')}
$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`glide-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('备份已导出')};
$('#importButton').onclick=()=>$('#importInput').click();$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.categories)||!data.categories.length)throw Error();if(!confirm('导入将覆盖当前导航数据，继续吗？'))return;state=data;state.active=state.categories.some(c=>c.id===state.active)?state.active:state.categories[0].id;save('备份已导入');render()}catch{toast('文件格式不正确')}finally{e.target.value=''}};
$('#themeButton').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';state.theme=dark?'light':'dark';save(dark?'已切换浅色模式':'已切换深色模式');applyTheme()};
$('#iconSize').addEventListener('input',e=>{state.iconSize=Number(e.target.value);applyIconSize();save()});$('#iconSize').addEventListener('change',()=>toast('图标大小已保存'));
function openSidebar(){els.sidebar.classList.add('open');els.scrim.classList.add('show')}function closeSidebar(){els.sidebar.classList.remove('open');els.scrim.classList.remove('show')}$('#openSidebar').onclick=openSidebar;$('#closeSidebar').onclick=closeSidebar;els.scrim.onclick=closeSidebar;
let touchTimer,touchCard;els.grid.addEventListener('touchstart',e=>{touchCard=e.target.closest('.site-card');if(!touchCard||e.target.closest('.edit'))return;touchTimer=setTimeout(()=>{openSite(touchCard.dataset.id,touchCard.dataset.category);navigator.vibrate?.(20)},600)},{passive:true});['touchend','touchmove','touchcancel'].forEach(x=>els.grid.addEventListener(x,()=>clearTimeout(touchTimer),{passive:true}));
matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',applyTheme);render();
