const KEY='glide-bookmarks-v1';
const ADMIN_USER='admin';
const API_URL='';
const palette=[['#5d7cff','#8a62ec'],['#ff7b6f','#ffad64'],['#20bfa9','#54d48e'],['#3975ee','#52b3ff'],['#bb5ee8','#f377b7'],['#364457','#79879a']];
const defaults={theme:'auto',active:'common',categories:[
  {id:'common',name:'常用',sites:[site('Apple','https://www.apple.com/cn/',''),site('百度','https://www.baidu.com/','百'),site('哔哩哔哩','https://www.bilibili.com/','▶')]},
  {id:'ai',name:'AI 工具',sites:[site('ChatGPT','https://chatgpt.com/','✦'),site('Claude','https://claude.ai/','C'),site('Perplexity','https://www.perplexity.ai/','P')]},
  {id:'dev',name:'开发工具',sites:[site('GitHub','https://github.com/','GH'),site('MDN','https://developer.mozilla.org/','MDN'),site('Vercel','https://vercel.com/','▲')]},
  {id:'media',name:'影音',sites:[site('YouTube','https://www.youtube.com/','▶'),site('Spotify','https://open.spotify.com/','●')]},
  {id:'mail',name:'邮箱',sites:[site('Gmail','https://mail.google.com/','M'),site('Outlook','https://outlook.live.com/','O')]},
  {id:'cloud',name:'云服务',sites:[site('iCloud','https://www.icloud.com/','☁'),site('Google Drive','https://drive.google.com/','△')]}
]};
function site(name,url,icon=''){return{id:uid(),name,url,icon}}
function uid(){return Math.random().toString(36).slice(2,10)}
function clone(v){return JSON.parse(JSON.stringify(v))}
let state=load();let query='';let dragged=null;let toastTimer;let pendingAddCategory='';let autoFilled={icon:''};let adminToken=sessionStorage.getItem('glide-admin-token')||'';let adminUnlocked=!!adminToken;let cloudReady=false;let saveTimer;
function clearAdminToken(){adminToken='';adminUnlocked=false;sessionStorage.removeItem('glide-admin-token')}
const $=s=>document.querySelector(s);const els={list:$('#categoryList'),grid:$('#siteGrid'),title:$('#pageTitle'),count:$('#siteCount'),empty:$('#emptyState'),search:$('#searchInput'),siteDialog:$('#siteDialog'),categoryDialog:$('#categoryDialog')};
function mergeReference(v){if((v.referenceDataVersion||0)>=REFERENCE_DATA_VERSION)return v;if(v.categories.some(c=>c.id.startsWith('ref-cat-')))return v;const oldDefaultIds=new Set(['common','ai','dev','media','mail','cloud']);const custom=v.categories.filter(c=>!oldDefaultIds.has(c.id)&&!c.id.startsWith('ref-cat-'));v.categories=clone(referenceCategories).concat(custom);v.active=v.categories[0].id;v.referenceDataVersion=REFERENCE_DATA_VERSION;delete v.iconSize;localStorage.setItem(KEY,JSON.stringify(v));return v}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.categories?.length)return mergeReference(v)}catch{}return mergeReference(clone(defaults))}
function save(message){localStorage.setItem(KEY,JSON.stringify(state));if(message)toast(message);if(adminUnlocked&&cloudReady){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCloudState(),180)}}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(adminToken)headers.Authorization=`Bearer ${adminToken}`;const response=await fetch(API_URL+path,{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'云端服务请求失败');return body}
async function loadCloudState(){try{const cloud=await api('/api/state');cloudReady=true;if(cloud?.categories?.length){state=cloud;state.referenceDataVersion=REFERENCE_DATA_VERSION;delete state.iconSize;localStorage.setItem(KEY,JSON.stringify(state));render()}}catch{toast('暂时无法连接云端，正在使用本地数据')}}
async function saveCloudState(){try{await api('/api/state',{method:'PUT',body:JSON.stringify(state)})}catch(error){if(/登录已失效/.test(error.message)){clearAdminToken();render()}toast(error.message)}}
function toast(msg){const e=$('#toast');e.textContent=msg;if(!e.open)e.show();e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{e.classList.remove('show');if(e.open)e.close()},1700)}
function activeCategory(){return state.categories.find(c=>c.id===state.active)||state.categories[0]}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function host(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
function colors(id){let n=[...id].reduce((a,c)=>a+c.charCodeAt(0),0);return palette[n%palette.length]}
function render(){document.body.classList.toggle('admin-mode',adminUnlocked);$('#adminLabel').textContent=adminUnlocked?'管理中':'管理员';renderCategories();renderSites();applyTheme();applyBackground();initSortables()}
function categoryIcon(c){const icon=String(c.icon||'').trim();return icon?`<span class="category-icon" aria-hidden="true">${escapeHtml(icon)}</span>`:''}
function renderCategories(){els.list.innerHTML=state.categories.map(c=>`<button class="category ${c.id===state.active?'active':''}" data-id="${c.id}" draggable="${adminUnlocked}">${categoryIcon(c)}<span>${escapeHtml(c.name)}</span><span class="cat-edit" role="button" aria-label="编辑 ${escapeHtml(c.name)}">···</span></button>`).join('')}
function displayIcon(s){const icon=String(s.icon||'').trim();return /google\.com\/s2\/favicons/i.test(icon)?`/api/favicon?domain=${encodeURIComponent(host(s.url))}&hd=1`:icon}
function siteCard(s){const [a,b]=colors(s.id),iconUrl=displayIcon(s);const isImage=/^(?:https?:\/\/|\/)/i.test(iconUrl);const icon=isImage?`<img src="${escapeHtml(iconUrl)}" alt="" onerror="this.parentElement.textContent='${escapeHtml(s.name[0]||'?')}'">`:escapeHtml(iconUrl||s.name[0]||'?');const detail=s.detail?`<span class="site-detail"><small>详情</small><strong>${escapeHtml(s.detail)}</strong></span>`:'';return `<article class="site-card" draggable="${adminUnlocked}" data-id="${s.id}" data-category="${s.categoryId}" style="--icon-a:${a};--icon-b:${b}"><button class="edit" aria-label="编辑 ${escapeHtml(s.name)}">•••</button><a class="site-link" href="${escapeHtml(s.url)}" target="_blank" rel="noopener"><span class="site-icon">${icon}</span><span class="site-name">${escapeHtml(s.name)}</span>${detail}</a></article>`}
function renderSites(){if(query){const sites=state.categories.flatMap(c=>c.sites.map(s=>({...s,categoryId:c.id}))).filter(s=>(s.name+' '+s.url).toLowerCase().includes(query.toLowerCase()));els.title.textContent='搜索结果';els.count.textContent=`${sites.length} 个网站`;els.grid.innerHTML=`<section class="category-section search-results"><div class="site-grid">${sites.map(siteCard).join('')}</div></section>`;els.empty.hidden=sites.length>0;return}const total=state.categories.reduce((n,c)=>n+c.sites.length,0);els.grid.innerHTML=state.categories.map(c=>`<section class="category-section" id="category-${c.id}" data-category="${c.id}"><header class="section-head"><h2>${categoryIcon(c)}${escapeHtml(c.name)}</h2></header><div class="site-grid">${c.sites.map(s=>siteCard({...s,categoryId:c.id})).join('')}<button class="add-bookmark-card" data-category="${c.id}" aria-label="在${escapeHtml(c.name)}中新增收藏"><span class="add-bookmark-icon">＋</span><span>新增收藏</span></button></div></section>`).join('');els.empty.hidden=total>0;setActiveCategory(state.active,false);requestAnimationFrame(syncCategoryFromScroll)}
function setActiveCategory(id,scrollLabel=true){const cat=state.categories.find(c=>c.id===id);if(!cat)return;state.active=id;els.title.textContent=cat.name;els.count.textContent=`${cat.sites.length} 个网站`;els.list.querySelectorAll('.category').forEach(row=>row.classList.toggle('active',row.dataset.id===id));if(scrollLabel){const row=els.list.querySelector(`[data-id="${CSS.escape(id)}"]`);if(row&&els.list.scrollWidth>els.list.clientWidth){const left=row.offsetLeft-(els.list.clientWidth-row.offsetWidth)/2;els.list.scrollTo({left:Math.max(0,left),behavior:'smooth'})}}}
let scrollFrame;function syncCategoryFromScroll(){if(query)return;const sections=[...els.grid.querySelectorAll('.category-section[data-category]')];if(!sections.length)return;const atBottom=innerHeight+scrollY>=document.documentElement.scrollHeight-4;if(atBottom){const last=sections.at(-1);if(last.dataset.category!==state.active)setActiveCategory(last.dataset.category);return}const guide=184;let current=sections[0];for(const section of sections){if(section.getBoundingClientRect().top<=guide)current=section;else break}if(current.dataset.category!==state.active)setActiveCategory(current.dataset.category)}window.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=null;syncCategoryFromScroll()})},{passive:true});
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='auto'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function applyBackground(){const bg=$('.aurora'),url=state.backgroundUrl||'',isBlack=/^(black|#0{3}|#0{6})$/i.test(url)||/placehold\.co\/[^?#]*\/0{6}\/0{6}|plain-black-wallpaper/i.test(url);bg.classList.toggle('solid-black',isBlack);bg.classList.toggle('custom-background',!!url&&!isBlack);bg.style.backgroundImage=url&&!isBlack?`linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.3)),url("${url.replace(/["\\]/g,'')}")`:''}
function fillCategories(selected){$('#siteCategory').innerHTML=state.categories.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}
function openSite(siteId,categoryId=state.active){if(!adminUnlocked)return;const cat=state.categories.find(c=>c.id===categoryId);const s=cat?.sites.find(x=>x.id===siteId);autoFilled={icon:''};$('#siteDialogTitle').textContent=s?'编辑网站':'添加网站';$('#siteId').value=s?.id||'';$('#siteName').value=s?.name||'';$('#siteUrl').value=s?.url||'';$('#siteIcon').value=s?.icon||'';$('#siteDetail').value=s?.detail||'';fillCategories(categoryId);$('#deleteSite').hidden=!s;els.siteDialog.showModal();setTimeout(()=>$('#siteName').focus(),50)}
function setAutoField(selector,key,value){const field=$(selector);if(!field.value.trim()||field.value===autoFilled[key]){field.value=value;autoFilled[key]=value}}
function autoCompleteSite(){let raw=$('#siteUrl').value.trim();if(!raw)return;try{if(!/^https?:\/\//i.test(raw))raw='https://'+raw;const url=new URL(raw),hostname=url.hostname.replace(/^www\./,'');$('#siteUrl').value=url.href;setAutoField('#siteIcon','icon',`/api/favicon?domain=${encodeURIComponent(hostname)}&hd=1`);toast('已自动添加网站图标')}catch{toast('请输入正确的网址')}}
$('#siteUrl').addEventListener('change',autoCompleteSite);$('#siteUrl').addEventListener('blur',autoCompleteSite);
function openCategory(id=''){if(!adminUnlocked)return;const c=state.categories.find(x=>x.id===id);$('#categoryDialogTitle').textContent=c?'编辑分类':'新建分类';$('#categoryId').value=c?.id||'';$('#categoryName').value=c?.name||'';$('#categoryIcon').value=c?.icon||'';syncCategoryIconPicker();$('#deleteCategory').hidden=!c;els.categoryDialog.showModal();setTimeout(()=>$('#categoryName').focus(),50)}
$('#siteClose').onclick=$('#siteCancel').onclick=()=>els.siteDialog.close();
$('#categoryClose').onclick=$('#categoryCancel').onclick=()=>els.categoryDialog.close();
els.list.addEventListener('click',e=>{const row=e.target.closest('.category');if(!row)return;if(e.target.closest('.cat-edit'))openCategory(row.dataset.id);else{query='';els.search.value='';setActiveCategory(row.dataset.id);const section=document.querySelector(`#category-${CSS.escape(row.dataset.id)}`);if(section){const top=section.getBoundingClientRect().top+scrollY-166;scrollTo({top,behavior:'smooth'})}}});
$('#addCategory').onclick=()=>openCategory();$('#addSite').onclick=()=>openSite('');$('#emptyAdd').onclick=()=>openSite('');
$('#categoryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#categoryId').value,name=$('#categoryName').value.trim(),icon=$('#categoryIcon').value.trim();if(!name)return;if(id){const c=state.categories.find(c=>c.id===id);c.name=name;c.icon=icon}else{const c={id:uid(),name,icon,sites:[]};state.categories.push(c);state.active=c.id}save(id?'分类已更新':'分类已创建');els.categoryDialog.close();render()});
$('#deleteCategory').onclick=()=>{const id=$('#categoryId').value,c=state.categories.find(x=>x.id===id);if(state.categories.length===1)return toast('至少保留一个分类');if(c.sites.length&&!confirm(`删除“${c.name}”及其中 ${c.sites.length} 个网站？`))return;state.categories=state.categories.filter(x=>x.id!==id);if(state.active===id)state.active=state.categories[0].id;save('分类已删除');els.categoryDialog.close();render()};
$('#siteForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#siteId').value,target=$('#siteCategory').value;let url=$('#siteUrl').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;const data={name:$('#siteName').value.trim(),url,icon:$('#siteIcon').value.trim(),detail:$('#siteDetail').value.trim()};if(id){let found,from;state.categories.forEach(c=>{const i=c.sites.findIndex(s=>s.id===id);if(i>=0){found=c.sites.splice(i,1)[0];from=c.id}});state.categories.find(c=>c.id===target).sites.push({...found,...data});if(from!==target)state.active=target}else state.categories.find(c=>c.id===target).sites.push({id:uid(),...data});save(id?'网站已更新':'网站已添加');els.siteDialog.close();render()});
$('#deleteSite').onclick=()=>{const id=$('#siteId').value;state.categories.forEach(c=>c.sites=c.sites.filter(s=>s.id!==id));save('网站已删除');els.siteDialog.close();render()};
els.grid.addEventListener('click',e=>{const card=e.target.closest('.site-card');if(card&&e.target.closest('.edit')){e.preventDefault();openSite(card.dataset.id,card.dataset.category)}});
els.grid.addEventListener('click',e=>{const add=e.target.closest('.add-bookmark-card');if(!add)return;pendingAddCategory=add.dataset.category;state.active=pendingAddCategory;if(adminUnlocked){openSite('',pendingAddCategory);pendingAddCategory=''}else openAdminDialog()});
els.search.addEventListener('input',e=>{query=e.target.value.trim();renderSites()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();els.search.focus()}});
// ===== SortableJS 拖拽（mac 工作台式：让位动画 + 拖拽放大半透明） =====
let sortables=[];
let draggingSite=false;
function highlightCatAt(x,y){els.list.querySelectorAll('.category').forEach(cEl=>{const r=cEl.getBoundingClientRect();cEl.classList.toggle('cat-drop-target',x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom)})}
function clearCatHighlight(){els.list.querySelectorAll('.cat-drop-target').forEach(cEl=>cEl.classList.remove('cat-drop-target'))}
document.addEventListener('pointermove',e=>{if(draggingSite&&typeof e.clientX==='number')highlightCatAt(e.clientX,e.clientY)});
function initSortables(){sortables.forEach(s=>s.destroy());sortables=[];if(query||!adminUnlocked)return;document.querySelectorAll('.category-section .site-grid').forEach(grid=>{sortables.push(new Sortable(grid,{group:'glide-sites',animation:180,draggable:'.site-card',filter:'.add-bookmark-card',ghostClass:'site-ghost',chosenClass:'site-chosen',dragClass:'site-drag',delay:300,delayOnTouchOnly:true,onStart:()=>{draggingSite=true},onEnd:evt=>{draggingSite=false;const x=evt.clientX??evt.originalEvent?.clientX,y=evt.clientY??evt.originalEvent?.clientY;let targetEl=null;if(typeof x==='number'&&typeof y==='number')els.list.querySelectorAll('.category').forEach(cEl=>{const r=cEl.getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom)targetEl=cEl});clearCatHighlight();if(targetEl){const id=evt.item.dataset.id;let moved=null;state.categories.forEach(c=>{const i=c.sites.findIndex(s=>s.id===id);if(i>=0)moved=c.sites.splice(i,1)[0]});if(moved){const target=state.categories.find(c=>c.id===targetEl.dataset.id)||state.categories.find(c=>c.id===state.active)||state.categories[0];target.sites.push(moved);save('网站已移动');render()}return}syncSitesFromDom();const fromId=evt.from.closest('.category-section')?.dataset.category,toId=evt.to.closest('.category-section')?.dataset.category;save(fromId===toId?'网站顺序已保存':'网站已移动');render()}}))});sortables.push(new Sortable(els.list,{animation:180,draggable:'.category',filter:'.cat-edit',group:'glide-cats',ghostClass:'cat-ghost',chosenClass:'cat-chosen',dragClass:'cat-drag',delay:300,delayOnTouchOnly:true,onEnd:()=>{const domOrder=[...els.list.querySelectorAll('.category')].map(c=>c.dataset.id),byId=new Map(state.categories.map(c=>[c.id,c]));state.categories=domOrder.map(id=>byId.get(id)).filter(Boolean);save('分类顺序已保存');render()}}))}
function syncSitesFromDom(){const allById=new Map();state.categories.forEach(c=>c.sites.forEach(s=>allById.set(s.id,s)));state.categories.forEach(cat=>{const section=document.querySelector(`#category-${CSS.escape(cat.id)}`);if(!section)return;const domOrder=[...section.querySelectorAll('.site-card')].map(c=>c.dataset.id);cat.sites=domOrder.map(id=>allById.get(id)).filter(Boolean)})}
$('#themeButton').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';state.theme=dark?'light':'dark';save(dark?'已切换浅色模式':'已切换深色模式');applyTheme()};
// 分类图标：微信表情包式选择器（点击选中，可自定义输入）
const iconPicker=$('#categoryIconPicker'),categoryIconInput=$('#categoryIcon');
function syncCategoryIconPicker(){iconPicker.querySelectorAll('.emoji-option').forEach(x=>x.classList.toggle('sel',x.dataset.icon===categoryIconInput.value))}
iconPicker.addEventListener('click',e=>{const b=e.target.closest('.emoji-option');if(!b)return;categoryIconInput.value=b.dataset.icon;syncCategoryIconPicker()});
categoryIconInput.addEventListener('input',syncCategoryIconPicker);
const groupExpandButton=$('#groupExpandButton');groupExpandButton.onclick=()=>{const strip=document.querySelector('.category-strip'),expanded=strip.classList.toggle('is-expanded');groupExpandButton.setAttribute('aria-expanded',String(expanded));groupExpandButton.setAttribute('aria-label',expanded?'收起全部分组':'展开全部分组')};
function openAdminDialog(){$('#adminDialogTitle').textContent='管理员登录';$('#adminSubmitLabel').textContent='登录';$('#adminUser').value=ADMIN_USER;const savedPass=localStorage.getItem('glide-admin-pass')||'';$('#adminPassword').value=savedPass;$('#rememberLogin').checked=!!savedPass;$('#adminPassword').placeholder='未设置密码时可留空';$('#adminError').hidden=true;$('#adminError').textContent='密码错误';resetPasswordVisibility($('#adminDialog'));$('#adminDialog').showModal();setTimeout(()=>$('#adminPassword').focus(),50)}
$('#adminToggle').onclick=()=>{if(adminUnlocked){clearAdminToken();toast('已退出管理模式');render()}else openAdminDialog()};
$('#logoutButton').onclick=()=>{clearAdminToken();toast('已退出管理模式');render()};
$('#adminForm').addEventListener('submit',async e=>{e.preventDefault();$('#adminError').hidden=true;try{const result=await api('/api/login',{method:'POST',body:JSON.stringify({user:ADMIN_USER,password:$('#adminPassword').value})});const remember=$('#rememberLogin').checked,pass=$('#adminPassword').value;if(remember)localStorage.setItem('glide-admin-pass',pass);else localStorage.removeItem('glide-admin-pass');sessionStorage.setItem('glide-admin-token',result.token);adminToken=result.token;adminUnlocked=true;$('#adminDialog').close();toast(remember?'已记住密码':'管理模式已开启');render();const cloud=await api('/api/state');if(!cloud)await saveCloudState();if(pendingAddCategory){const categoryId=pendingAddCategory;pendingAddCategory='';openSite('',categoryId)}}catch(error){$('#adminError').textContent=error.message;$('#adminError').hidden=false}});
$('#adminClose').onclick=()=>$('#adminDialog').close();$('#adminCancel').onclick=()=>$('#adminDialog').close();
function passwordFieldName(target){return target==='adminPassword'?'密码':target==='currentPassword'?'当前密码':target==='newPassword'?'新密码':'确认密码'}function resetPasswordVisibility(scope){scope.querySelectorAll('.password-toggle').forEach(button=>{const input=document.getElementById(button.dataset.passwordTarget);if(input)input.type='password';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',`显示${passwordFieldName(button.dataset.passwordTarget)}`);button.classList.remove('is-visible')})}document.addEventListener('click',e=>{const button=e.target.closest('.password-toggle');if(!button)return;const input=document.getElementById(button.dataset.passwordTarget);if(!input)return;const visible=input.type==='text';input.type=visible?'password':'text';button.setAttribute('aria-pressed',String(!visible));button.setAttribute('aria-label',`${visible?'显示':'隐藏'}${passwordFieldName(button.dataset.passwordTarget)}`);button.classList.toggle('is-visible',!visible)});
$('#changePasswordButton').onclick=()=>{$('#passwordForm').reset();$('#passwordError').hidden=true;resetPasswordVisibility($('#passwordDialog'));$('#passwordDialog').showModal();setTimeout(()=>$('#currentPassword').focus(),50)};$('#passwordClose').onclick=()=>$('#passwordDialog').close();$('#passwordCancel').onclick=()=>$('#passwordDialog').close();$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();const current=$('#currentPassword').value,next=$('#newPassword').value,confirmPassword=$('#newPasswordConfirm').value;if(next!==confirmPassword){$('#passwordError').textContent='两次输入的新密码不一致';$('#passwordError').hidden=false;return}try{await api('/api/password',{method:'PUT',body:JSON.stringify({currentPassword:current,newPassword:next})});$('#passwordDialog').close();toast(next?'管理员密码已更新':'管理员密码已清除')}catch(error){$('#passwordError').textContent=error.message;$('#passwordError').hidden=false}});
function updateBackgroundPreview(){const url=$('#backgroundUrl').value.trim(),preview=$('#backgroundPreview');preview.style.backgroundImage=url?`url("${url.replace(/["\\]/g,'')}")`:'';preview.classList.toggle('has-image',!!url)}$('#backgroundButton').onclick=()=>{$('#backgroundUrl').value=state.backgroundUrl||'';updateBackgroundPreview();$('#backgroundDialog').showModal()};$('#backgroundClose').onclick=()=>$('#backgroundDialog').close();$('#backgroundCancel').onclick=()=>$('#backgroundDialog').close();$('#backgroundUrl').addEventListener('input',updateBackgroundPreview);$('#backgroundForm').addEventListener('submit',e=>{e.preventDefault();state.backgroundUrl=$('#backgroundUrl').value.trim();save('网页背景已更新');$('#backgroundDialog').close();applyBackground()});$('#resetBackground').onclick=()=>{state.backgroundUrl='';save('已恢复默认背景');$('#backgroundUrl').value='';updateBackgroundPreview();$('#backgroundDialog').close();applyBackground()};
// ===== 备注生成（AI 生成中文描述） =====
$('#aiGenerateDetail').onclick=async()=>{const name=$('#siteName').value.trim();const url=$('#siteUrl').value.trim();if(!name||!/^https?:\/\//i.test(url)){toast('请先填写名称和网址');return}const btn=$('#aiGenerateDetail');btn.disabled=true;btn.textContent='⏳ 生成中…';try{const result=await api('/api/remark',{method:'POST',body:JSON.stringify({url,name})});$('#siteDetail').value=result.text||'';toast('备注已生成')}catch(error){toast(error.message)}finally{btn.disabled=false;btn.textContent='✨ 生成备注'}};

// ===== AI 设置 =====
function toggleAIFields(){const p=$('#aiProvider').value;$('#aiKeyField').hidden=p==='workers-ai';$('#aiBaseUrlField').hidden=p!=='openai';$('#aiModel').placeholder=p==='workers-ai'?'默认 mistral-small（可留空）':p==='openai'?'如 gpt-3.5-turbo':'如 gemini-1.5-flash'}
$('#aiProvider').addEventListener('change',toggleAIFields);
function fillAIConfig(config){$('#aiProvider').value=config.provider||'workers-ai';$('#aiModel').value=config.model||'';$('#aiApiKey').value=config.apiKey||'';$('#aiBaseUrl').value=config.baseUrl||'';toggleAIFields()}
$('#aiSettingsButton').onclick=()=>{if(!adminUnlocked){openAdminDialog();return}$('#aiError').hidden=true;api('/api/ai/config').then(fillAIConfig).catch(()=>fillAIConfig({provider:'workers-ai',apiKey:'',baseUrl:'',model:''}));$('#aiDialog').showModal()};
$('#aiClose').onclick=$('#aiCancel').onclick=()=>$('#aiDialog').close();
$('#aiForm').addEventListener('submit',async e=>{e.preventDefault();const config={provider:$('#aiProvider').value,apiKey:$('#aiApiKey').value.trim(),baseUrl:$('#aiBaseUrl').value.trim(),model:$('#aiModel').value.trim()};try{await api('/api/ai/config',{method:'PUT',body:JSON.stringify(config)});$('#aiDialog').close();toast('AI 设置已保存')}catch(error){$('#aiError').textContent=error.message;$('#aiError').hidden=false}});

// ===== 批量生成备注 =====
$('#aiBatchButton').onclick=()=>{const total=state.categories.reduce((n,c)=>n+c.sites.length,0);$('#batchTotal').textContent=`${total} 个`;$('#batchProgress').hidden=true;$('#batchDesc').innerHTML='将为 <b>全部书签</b> 用 AI 生成中文备注，<b>可能覆盖已有备注</b>。';$('#batchDialog').showModal()};
$('#batchClose').onclick=$('#batchCancel').onclick=()=>$('#batchDialog').close();
$('#batchForm').addEventListener('submit',async e=>{e.preventDefault();await runBatch()});
async function runBatch(){const sites=state.categories.flatMap(c=>c.sites.map(s=>({...s,categoryId:c.id})));const progress=$('#batchProgress');const startBtn=$('#batchStart');progress.hidden=false;startBtn.disabled=true;$('#batchDesc').textContent=`正在为 ${sites.length} 个书签生成备注，请稍候…`;let done=0,failed=0;for(const s of sites){try{const result=await api('/api/remark',{method:'POST',body:JSON.stringify({url:s.url,name:s.name})});const cat=state.categories.find(c=>c.id===s.categoryId);const site=cat?.sites.find(x=>x.id===s.id);if(site&&result.text)site.detail=result.text;done++}catch{failed++;if(failed>5){toast('连续失败过多，已停止');break}}progress.textContent=`进度 ${done+failed}/${sites.length}（成功 ${done}，失败 ${failed}）`}save('批量备注已生成');render();$('#batchDialog').close();progress.hidden=true;startBtn.disabled=false;toast(`批量生成完成：成功 ${done}，失败 ${failed}`)}

// 分类栏：初始左端不虚化，向左滑动后左端渐隐提示（配合 CSS mask）
const catList=$('#categoryList');function updateCatMask(){catList.classList.toggle('scrolled',catList.scrollLeft>0)}catList.addEventListener('scroll',updateCatMask);

matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',applyTheme);render();loadCloudState();updateCatMask();
